version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x

  pre_build:
    commands:
      - chmod +x techmax/build-image.sh techmax/push-image.sh
      - ./techmax/build-image.sh

  build:
    commands:
      - ./techmax/push-image.sh
